stages:
  - deploy
  - apply

image: dtzar/helm-kubectl:3.13

variables:
  KUBE_CONTEXT: otus/search_engine_deploy:yc-k8s

deploy:
  stage: deploy
  variables:
    KUBE_NAMESPACE: monitoring
  before_script:
    - helm repo add grafana https://grafana.github.io/helm-charts
    - helm repo update
    - kubectl config use-context ${KUBE_CONTEXT}
  script:
    - echo "Deploy ${KUBE_NAMESPACE}"
    - helm upgrade --install --wait --atomic
        --namespace "$KUBE_NAMESPACE" --create-namespace
        --values monitoring-values.yaml
        loki-stack grafana/loki-stack
    - kubectl get secret --namespace monitoring loki-stack-grafana -o jsonpath="{.data.admin-password}" | base64 -d ; echo
  only:
    - tags
  except:
    - branches

apply:
  stage: apply
  before_script:
    - kubectl config use-context ${KUBE_CONTEXT}
  script:
    - echo "Apply grafana-ingress"
    - kubectl apply -f grafana-ingress.yaml
  only:
    - main
  except:
    - triggers
