stages:
  - test
  - deploy

deploy:
  stage: deploy
  image: dtzar/helm-kubectl:3.13
  variables:
    KUBE_CONTEXT: ${CI_PROJECT_PATH}:yc-k8s
    KUBE_NAMESPACE: monitoring
  script:
    - kubectl config get-contexts
    - kubectl config use-context ${KUBE_CONTEXT}
    - kubectl describe namespace "${KUBE_NAMESPACE}" || kubectl create namespace "${KUBE_NAMESPACE}"
    - echo "Deploy ${KUBE_NAMESPACE}"
    - helm upgrade --install loki-stack grafana/loki-stack --repo https://grafana.github.io/helm-charts --namespace "$KUBE_NAMESPACE" --values monitoring-values.yaml
    - kubectl apply -f grafana-ingress.yaml
    - kubectl get secret --namespace monitoring loki-stack-grafana -o jsonpath="{.data.admin-password}" | base64 --decode ; echo
  only:
    refs:
      - main
  except:
    - triggers

test:
  stage: test
  variables:
    GIT_STRATEGY: none
  script:
    - env
    - exit 0
  only:
    - triggers
    - branches
  except:
    - main
