stages:
  - test
  - deploy

deploy:
  stage: deploy
  image: dtzar/helm-kubectl:3.13
  variables:
    KUBE_CONTEXT: otus/search_engine_deploy:yc-k8s
    KUBE_NAMESPACE: monitoring
  before_script:
    - helm repo add grafana https://grafana.github.io/helm-charts
    - helm repo update
  script:
    - kubectl config use-context ${KUBE_CONTEXT}
    - echo "Deploy ${KUBE_NAMESPACE}"
    - helm upgrade --install --wait --atomic
        --namespace "$KUBE_NAMESPACE" --create-namespace
        --values monitoring-values.yaml
        loki-stack grafana/loki-stack
    - kubectl apply -f grafana-ingress.yaml
    - kubectl get secret --namespace monitoring loki-stack-grafana -o jsonpath="{.data.admin-password}" | base64 -d ; echo
  only:
    refs:
      - main
  except:
    - triggers

test:
  stage: test
  variables:
    GIT_STRATEGY: none
  script:
    - env
    - exit 0
  only:
    - triggers
    - branches
  except:
    - main
