{
 "title": "Crawler & UI",
 "description": "Crawler & UI summary",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Crawler charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Crawler parsed pages",
   "type": "timeseries",
   "description": "Total Crawler parsed pages",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{namespace=\"prod\", __name__=\"crawler_pages_parsed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Crawler page parse time",
   "type": "timeseries",
   "description": "Total Crawler page parse time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "{namespace=\"prod\", __name__=\"crawler_page_parse_time_count\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Crawler site connection time",
   "type": "timeseries",
   "description": "Total Crawler site connection time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "{namespace=\"prod\", __name__=\"crawler_site_connection_time_count\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "UI charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "UI web pages served",
   "type": "timeseries",
   "description": "Total UI web pages served",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{namespace=\"prod\", __name__=\"web_pages_served\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UI web pages gen time",
   "type": "timeseries",
   "description": "SummaryUI web pages gen time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "expr": "{namespace=\"prod\", __name__=\"web_page_gen_time_sum\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}